language: c++

os:
  - linux
  - osx

dist: xenial
sudo: false

script:
  - make
  - if [ "$TRAVIS_TAG" ]; then
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        zip Macos.zip libmodio.dylib;
      else
        zip Linux.zip libmodio.so;
      fi
    fi

deploy:
  - provider: releases
    api_key: "${token}"
    file:
      - "Linux.zip"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME != "osx"
  - provider: releases
    api_key: "${token}"
    file:
      - "Macos.zip"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME == "osx"
